### ISSUE TITLE
Hardwatervalue needed

### ISSUE THREAD

**Issue by danielegger1** [www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge#4]
Hallo

es wäre super, wenn man auch den Hartwasserwert automatisch ausrechnet, für das Energy Dashboard könnte man dann Hart / Weichwasserverbrauch verwenden und erhält somit die Summe.
Wäre cool, wenn Sie das ergänzen könnten :)

Code Änderungen:

total_water = entity("Gesamtwasserverbrauch", "mdi:water", "total_increasing", "m³")
total_softwater = entity("Gesamtweichwasserverbrauch", "mdi:water-outline", "total_increasing", "m³")
total_hardwater = entity("Gesamthartwasserverbrauch", "mdi:water-circle", "total_increasing", "m³")

            #Total Water Consumption #8
            val = response_json["data"][0]["data"][0]["data"]["8"]["data"]
            total_water.value = float(le_hex_to_int(val[0:8]))/1000

            #Total Softwater Consumption #9
            val = response_json["data"][0]["data"][0]["data"]["9"]["data"]
            total_softwater.value = float(le_hex_to_int(val[0:8]))/1000

            #Total Hardwater Consumption (Total Water - Softwater)
            total_hardwater.value = round(total_water.value - total_softwater.value, 3)

**Comment by danielegger1** [comment]
Habe die mdi`s noch geändert, dann ist es stimmiger

total_water = entity("Gesamtwasserverbrauch", "mdi:water-circle", "total_increasing", "m³")
total_softwater = entity("Gesamtweichwasserverbrauch", "mdi:water-outline", "total_increasing", "m³")
total_hardwater = entity("Gesamthartwasserverbrauch", "mdi:water", "total_increasing", "m³")

**Comment by www-ShapeLabs-de** [comment]
Moin,

eigentlich ist der "Hartwasserverbrauch" ja der Gesamtwasserverbrauch. 
Die Anlage funktioniert ja so, dass sie das Wasser erstmal auf nahezu 0°dH runterenthärtet und dann je nach Wunschhärtegrad wieder "Hartwasser" sprich "unenthärtetes Wasser" dazumixt.

Deshalb tue ich mich mit der Bezeichnung etwas schwer. ich würde es "total_mixed_hardwater" nennen. 

Aber ich kann es gerne einfügen, dann könnte man im Energy-Dashboard die Zusammensetzung des Wassers in den Balken sehen, wenn ich das richtig verstanden hab...

Viele Grüße

Henning

**Comment by danielegger1** [comment]
Genau um das geht es mir, damit ich die Zusammensetzung im Energie-Dashboard anzeigen kann, ist zwar nicht so relevant, aber trotzdem interessant zu sehen.
Der Name ist mir eigentlich gleich, grundsätzlich ist es ja der Anteil an Hartwasser (unverändertes Wasser) zum Weichwasser, auf 0 reduziert, Mixed Water ist eigentlich dann ja das Resultat, deswegen mein Namens-Vorschlag.
